## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
# do not run CI tests twice
branches:
  only:
    - master
os:
  - linux
julia:
  - 1
  # - nightly
notifications:
  email: false
git:
  depth: 99999999
# matrix:
#   allow_failures:
#     julia: nightly
dist: xenial
env:
  - GROUP=Core
  - GROUP=Stan
before_install: |
  if [[ "$GROUP" == "Stan" ]]; then
    url="https://github.com/stan-dev/cmdstan/releases/download/v2.21.0/cmdstan-2.21.0.tar.gz"
    curl -L "$url" | tar zxf -
    export JULIA_CMDSTAN_HOME="$(pwd)/cmdstan-2.21.0"
    make -C "$JULIA_CMDSTAN_HOME" build
  fi
jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
